// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows config is not set up.',
        );
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo81IWPMvTihcthSXTyGqEDZvjjsolxHE',
    appId: '1:807506092000:web:xxxxxxxxxxxx', // Web belum di-setup di JSON, biarkan placeholder
    messagingSenderId: '807506092000',
    projectId: 'wilyam-yazid-hamdi',
    authDomain: 'wilyam-yazid-hamdi.firebaseapp.com',
    storageBucket: 'wilyam-yazid-hamdi.firebasestorage.app',
  );

  // INI BAGIAN PALING PENTING UNTUK ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo81IWPMvTihcthSXTyGqEDZvjjsolxHE', // Dari JSON Anda
    appId: '1:807506092000:android:278437ff3d72549f00d585', // Dari JSON Anda (W3 Grocery)
    messagingSenderId: '807506092000',
    projectId: 'wilyam-yazid-hamdi',
    databaseURL: 'https://wilyam-yazid-hamdi.firebaseio.com',
    storageBucket: 'wilyam-yazid-hamdi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo81IWPMvTihcthSXTyGqEDZvjjsolxHE',
    appId: '1:807506092000:ios:xxxxxxxxxxxx',
    messagingSenderId: '807506092000',
    projectId: 'wilyam-yazid-hamdi',
    databaseURL: 'https://wilyam-yazid-hamdi.firebaseio.com',
    storageBucket: 'wilyam-yazid-hamdi.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo81IWPMvTihcthSXTyGqEDZvjjsolxHE',
    appId: '1:807506092000:ios:xxxxxxxxxxxx',
    messagingSenderId: '807506092000',
    projectId: 'wilyam-yazid-hamdi',
    databaseURL: 'https://wilyam-yazid-hamdi.firebaseio.com',
    storageBucket: 'wilyam-yazid-hamdi.firebasestorage.app',
  );
}